main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

#_user_bundle:
 #   resource: "@UserBundle/Resources/config/routing.yml"
  #  type: annotation

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
